version: '3.8'
services:
    myvault:
        build: "./vault"
        image: docker.io/vault:latest
        container_name: "vault"
        ports:
          - "8200:8200/tcp"
        volumes:
          - file:/vault/file:rw
          - vault_config:/vault/config
          - vault_policies:/vault/policies
          - vault_data:/vault/data
        environment:
          - VAULT_ADDR=http://0.0.0.0:8200
          - VAULT_API_ADDR=http://0.0.0.0:8200
          - VAULT_DEV_LISTEN_ADDRESS=http://0.0.0.0:8200
          - VAULT_DEV_ROOT_TOKEN_ID=myroot
#          - VAULT_DISABLE_MLOCK=true #mlock requires further configuration in non-root mode
        cap_add:
          - IPC_LOCK
        entrypoint: vault server -config=/vault/config/vault-config.hcl

volumes:
  file:
  vault_config:
  vault_policies:
  vault_data:
